;;;; Copyright (c) Frank James 2015 <frank.a.james@gmail.com>
;;;; This code is licensed under the MIT license.

;;; Autogenerated from frpc/gen/xfiles/key_prot.x at 2015-6-2 16:41:16 

;;;
;;; This file defines a keyserver (as defined in key_prot.x) to distribute secret/public keys for use with 
;;; AUTH-DES authentication flavour. 
;;; Essentially this is an RPC interface to the functionality in des.lisp.
;;; 

(defpackage #:keyserv
  (:use #:cl #:frpc)
  (:export #:call-null
           #:call-set
           #:call-encrypt
           #:call-decrypt
           #:call-gen
           #:call-get
           #:*keylist-path*))

(in-package #:keyserv)


(defxenum keystatus 
  (:success 0) 
  (:nosecret 1) 
  (:unknown 2)
  (:error 3))

(define-condition key-error (error)
  ((stat :initarg :stat :reader key-error-stat))
  (:report (lambda (c stream)
             (format stream "KEY-ERROR: ~A" (key-error-stat c)))))

(defconstant +hex-key-bytes+ 48)

(defxtype* des-block () (:array :octet 8))
(defxtype* keybuf () (:varray* :octet +hex-key-bytes+))

(defun integer-keybuf (integer)
  "Convert a bignum to a keybuffer"
  (do ((nums nil)
       (n integer (ash n -8)))
      ((zerop n) (apply #'vector (nreverse nums)))
    (push (mod n 256) nums)))

(defun keybuf-integer (keybuf)
  "Convert a keybuffer back to a bignum."
  (do ((i (1- (length keybuf)) (1- i))
       (n 0))
      ((< i 0) n)
    (setf n (+ (ash n 8) (aref keybuf i)))))

(defxtype* netnamestr () :string)

(defxtype* cryptkeyarg () 
  (:list netnamestr des-block)) ;; remotename deskey

(defxunion cryptkeyres (keystatus) 
  (:success des-block)
  (otherwise :void))

(defconstant +max-gids+ 16)

(defxtype* unixcred ()
  (:plist :uid :uint32
          :gid :uint32 
          :gids (:varray :uint32 +max-gids+)))

(defxunion getcredres (keystatus) 
  (:success unixcred)
  (otherwise :void))

(defprogram keyserv 100029)

;; ------------------------------

(defrpc call-null 0 :void :void
  (:program keyserv 1))

;; ----------------------------------------

(defrpc call-set 1 keybuf keystatus 
  (:program keyserv 1)
  (:arg-transformer (key) 
    (etypecase key 
      (integer (integer-keybuf key))
      (vector key)))
  (:transformer (res)
    (if (eq res :success) 
        nil
        (error 'key-error :stat res)))
  (:documentation "This is my secret key, store it for me."))

;; ---------------------------------

(defrpc call-encrypt 2 cryptkeyarg cryptkeyres 
  (:program keyserv 1)
  (:arg-transformer (netname key)
    (list netname key))
  (:transformer (res)
    (if (eq (xunion-tag res) :success)
        (xunion-val res)
        (error 'key-error :stat (xunion-tag res))))
  (:documentation "I want to talk to X, encrypt a conversation key for me."))

;; ---------------------------------

(defrpc call-decrypt 3 cryptkeyarg cryptkeyres 
  (:program keyserv 1)
  (:arg-transformer (netname key)
    (list netname key))
  (:transformer (res)
    (if (eq (xunion-tag res) :success)
        (xunion-val res)
        (error 'key-error :stat (xunion-tag res))))
  (:documentation "X just sent me a message, decrypt the conversation key for me."))

;; ---------------------------------

(defrpc call-gen 4 :void des-block 
  (:program keyserv 1)
  (:documentation "Generate a conversation key for me."))

;; ---------------------------------

;; don't support this yet
;;(defun handle-get (name)
;;  ;; lookup the unix creds for this netname string 
;;  (let ((creds (auth-or-fail)))
    
(defrpc call-get 5 netnamestr getcredres 
  (:program keyserv 1)
  (:arg-transformer (netname) netname)
  (:transformer (res)
    (if (eq (xunion-tag res) :success)
        (xunion-val res)
        (error 'key-error (xunion-tag res))))
  (:documentation "Get the UID, GID and GID-list for this netname."))

;; ----------------------------------------------
;; ----------------------------------------------

;; version 2

;;(defxtype* cryptkeyarg2 ()
;;  (:plist remotename netnamestr 
;;          remotekey netobj 
;;          deskey des-block))

;; (defxtype* key-netstarg ()
;;   (:plist st-priv-key keybuf 
;;           st-pub-key keybuf 
;;           st-netname netnamestr))

;; (defxunion key-netstres (keystatus) 
;;   (:key-success key-netstarg)
;;   (otherwise :void))



;; (defrpc call-null2 0 :void :void
;;   (:program keyserv 2))

;; (defrpc call-key-set 1 keybuf keystatus (:program keyserv 2))

;; (defrpc call-key-encrypt 2 cryptkeyarg cryptkeyres (:program keyserv 2))

;; (defrpc call-key-decrypt 3 cryptkeyarg cryptkeyres (:program keyserv 2))

;; (defrpc call-key-gen 4 :void des-block (:program keyserv 2))

;; (defrpc call-key-getcred 5 netnamestr getcredres (:program keyserv 2))

;; (defrpc call-key-encrypt-pk 6 cryptkeyarg2 cryptkeyres
;;              (:program keyserv 2))

;; (defrpc call-key-decrypt-pk 7 cryptkeyarg2 cryptkeyres
;;              (:program keyserv 2))

;; (defrpc call-key-net-put 8 key-netstarg keystatus (:program keyserv 2))

;; (defrpc call-key-net-get 9 :void key-netstres (:program keyserv 2))

;; (defrpc call-key-get-conv 10 keybuf cryptkeyres (:program keyserv 2))
