
;;; Autogenerated from c:/Users/frank/quicklisp/local-projects/frpc/auth/des/frpc-des.x at 2015-6-5 7:57:57 


(defpackage #:frpc-des
  (:use #:cl #:frpc)
  (:export #:call-list
           #:call-set
           #:call-get
           #:call-null))

(in-package #:frpc-des)

(defxtype* frpc-des-entry ()
  (:plist :name :string
	  :timestamp :uint64
	  :key (:varray* :octet)))

(defxtype frpc-des-entry-list ()
  ((stream)
   (read-xtype-list stream 'frpc-des-entry))
  ((stream list)
   (write-xtype-list stream 'frpc-des-entry list)))

(frpc:defprogram frpc-des-prog 814857052)

(frpc:defrpc call-null 0 :void :void 
  (:program frpc-des-prog 1))

(frpc:defrpc call-get 1 frpc-des-name frpc-des-entry
  (:program frpc-des-prog 1))

(frpc:defrpc call-set 2 frpc-des-entry :void
  (:program frpc-des-prog 1))

(frpc:defrpc call-list 3 :void (:optional frpc-des-entry-list)
  (:program frpc-des-prog 1))
