;;;; Copyright (c) Frank James 2015 <frank.a.james@gmail.com>
;;;; This code is licensed under the MIT license.

;;; Autogenerated from frpc/auth/des/frpc-des.x at 2015-6-5 7:57:57 

(in-package #:frpc-des)

;; this type just maps integers into buffer arrays for convenience
(defxtype frpc-des-keybuf ()
  ((stream)
   (let ((buff (frpc::read-octet-array stream)))
     (keybuf-integer buff)))
  ((stream integer)
   (frpc::write-octet-array stream (integer-keybuf integer))))

;; represents a database entry
(defxtype* frpc-des-entry ()
  (:plist :name :string
	  :public frpc-des-keybuf))

;; a list of database entries 
(defxtype frpc-des-entry-list ()
  ((stream)
   (read-xtype-list stream 'frpc-des-entry))
  ((stream list)
   (write-xtype-list stream 'frpc-des-entry list)))

;; a random program number I generated
(frpc:defprogram frpc-des-prog 814857052)

;; -----------------------------------

(frpc:defrpc call-null 0 :void :void 
  (:program frpc-des-prog 1)
  (:handler #'default-null-handler))

;; -----------------------------------

(defun handle-get (name)
  (find-public-key name))

(frpc:defrpc call-get 1 :string frpc-des-keybuf 
  (:program frpc-des-prog 1)
  (:arg-transformer (name) name)
  (:documentation "Get the public key for the named principal.")
  (:handler #'handle-get))

;; -----------------------------------

(defun auth-or-fail (name)
  ;; reject if not authenticated using DES for the same name as the person they are claiming to be
  (unless (eq (opaque-auth-flavour *rpc-remote-auth*) :auth-des)
    (frpc-log :trace "Not DES authenticated")
    (error 'rpc-auth-error))
  (let ((aname (rpc-auth-principal)))
    (unless (string-equal aname name)
      (frpc-log :trace "Auth name ~A doesn't match requested name ~A" aname name)
      (error 'rpc-auth-error))))

(defun handle-set (arg)
  (auth-or-fail (getf arg :name))
  (add-public-key (getf arg :name) (getf arg :public))
  nil)
  
(frpc:defrpc call-set 2 frpc-des-entry :void
  (:program frpc-des-prog 1)
  (:arg-transformer (name secret)
    (list :name name :public (des-public secret)))
  (:documentation "Set the public key for the principal named NAME. SECRET should be the secret key, only
the derived public key is sent to the remote database to be stored.")
  (:handler #'handle-set)

;; -----------------------------------

(defun handle-unset (name)
  (auth-or-fail name)
  (remove-public-key name)
  nil)
  
(frpc:defrpc call-unset 3 :string :void
  (:program frpc-des-prog 1)
  (:arg-transformer (name public)
    (list :name name :public public))
  (:documentation "Delete the public key entry for the named principal.")
  (:handler #'handle-set))

;; -----------------------------------

(defun handle-list (void)
  (declare (ignore void))
  (let ((entries (public-key-list)))
    (mapcar (lambda (entry)
	      (list :name (getf entry :name)
		    :public (getf entry :public)))
	    entries)))

(frpc:defrpc call-list 4 :void (:optional frpc-des-entry-list)
  (:program frpc-des-prog 1)
  (:documentation "List all database entries.")
  (:handler #'handle-list))
